### ISSUE TITLE
Review #1

### ISSUE THREAD

**Issue by FacundoEG** [DiegoVillalo/juego#1]
Hola Diego! ahí probé el juego y te quedo muy bueno! sabes que te quiero devolver algunas cosas que note.

![image](https://user-images.githubusercontent.com/79592789/131255548-082d7616-8448-426e-b699-8901e5f4e2f6.png)

Fíjate que te quedo como un "margen" abajo cuando llegas a la pantalla de los resultados, donde queda sobrando el fondo por atrás. Note que el div class="root" no llega a tomar todo el alto de la pantalla. 

Me gustaría sugerirte que de ultima, le canceles el "scroll" a la pantalla, ya que eso pasa mas que nada cuando scrolleas para abajo. O si no tratar de darle un alto en vh.

(El scroll lo podes "desabilitar" sin problema dándole un `"overflow: hidden"` al body.)

Además de eso, me llamo la atención ese texto que dice "puntajes" abajo de los botones, ya que rompe un poco el diseño.

Es un detalle estético solamente, en la jugabilidad quedo muy bien! me pareció muy copado el botón para reiniciar los resultados.

 Así que para mi LGTM!

**Comment by DiegoVillalo** [comment]
amigo creo que todo solucionado, si ves un detalle me escribes

**Comment by FacundoEG** [comment]
Diego ahi lo volvi a probar y te quedo hermoso! 
Te cierro el issue porque ya se soluciono si?

Saludos!
